# Generated by Django 5.1.6 on 2025-02-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='img',
            new_name='image',
        ),
    ]
