# Generated by Django 5.1.6 on 2025-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='created_at'),
        ),
    ]
