# Generated by Django 5.1.6 on 2025-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_time',
            field=models.DateField(),
        ),
    ]
